# Generated by Django 6.0.3 on 2026-06-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0023_purchases_supplier_purchaseitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hpp',
            field=models.FloatField(default=0),
        ),
    ]
