# Generated by Django 6.0.3 on 2026-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0026_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='hpp',
            field=models.FloatField(default=0),
        ),
    ]
