# Generated by Django 6.0.3 on 2026-06-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0027_salesitems_hpp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warrantyclaim',
            unique_together={('sale_id', 'product_id')},
        ),
    ]
